# Generated by Django 4.1.1 on 2022-09-15 13:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoDeConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Tipo de Contéudo')),
            ],
        ),
        migrations.CreateModel(
            name='blocoConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudo.tipodeconteudo')),
            ],
        ),
    ]
