# Generated by Django 4.1.1 on 2022-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blococonteudo',
            name='imagem',
            field=models.ImageField(default=1, upload_to='static_files/uploads'),
            preserve_default=False,
        ),
    ]
