# Generated by Django 4.1.1 on 2022-09-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_submenu_alter_menu_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='menu_principal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
            preserve_default=False,
        ),
    ]
