# Generated by Django 4.1.1 on 2022-09-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_submenu_menu_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='menu_principal',
        ),
        migrations.AddField(
            model_name='menu',
            name='subMenus',
            field=models.ManyToManyField(blank=True, null=True, to='menu.submenu'),
        ),
    ]
