# Generated by Django 4.1.1 on 2022-09-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_submenu_menu_principal_menu_submenus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='subMenus',
            field=models.ManyToManyField(blank=True, to='menu.submenu'),
        ),
    ]
