# Generated by Django 4.1.1 on 2022-09-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menu_submenus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
