# Generated by Django 4.1.1 on 2022-09-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menulateral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuLateral',
        ),
        migrations.AddField(
            model_name='submenu',
            name='novo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
