# Generated by Django 4.1.1 on 2022-09-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsheader',
            name='imagem',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemsheader',
            name='nome',
            field=models.CharField(max_length=70, verbose_name='Item'),
        ),
    ]
